format = 0

[[dependencies]]
name = "parsetoml"
commit = ""
origin = "git"
src = "github.com/nimparsers/parsetoml"
version = "0.7.2"
refr = ""
sub-dir = ""
src-dir = "src/parsetoml"
entrypoint = "../parsetoml.nim"
is-pseudo = false

