format = 0

[package]
origin      = "git"
authors     = ["Luyten Orion"]
description = "A new package manager for Skull!"
license     = "MIT"
#documentation = "https://your.docs.url/here"
source      = "https://github.com/Luyten-Orion/FaePkg"
homepage    = "https://github.com/Luyten-Orion/FaePkg"

[package.ext]
tags = ["nimskull", "package-manager", "cli"]

[forges.gh]
origin = "git"
host   = "github.com"

[sourcesets.main]
src-dir = "src"

[[dependencies]]
src     = "gh:NimParsers/parsetoml"
version = "0.7.2"

[[dependencies]]
src     = "gh:disruptek/gittyup"
version = "3.2.2"

[[dependencies]]
src     = "gh:disruptek/gram"
version = "0.4.1"

# TODO: Features section