format = 0

[package]
authors            = ["Luyten Orion"]
description        = "A new package manager for Skull!"
# SPDX identifier
license            = "MIT"
#documentation      = "https://your.docs.url/here"
source             = "https://github.com/Luyten-Orion/FaePkg"
homepage           = "https://github.com/Luyten-Orion/FaePkg"

[package.ext]
tags = ["nimskull", "package-manager", "cli"]

[dependencies.parsetoml]
src        = "gh:nimparsers/parsetoml"
version    = "0.7.2"
nimble     = true

#[dependencies.gittyup]
#src     = "gh:disruptek/gittyup"
#version = "3.2.2"

# TODO: Features section
