format = 0

[package]
origin             = "git"
authors            = ["Luyten Orion"]
description        = "A new package manager for Skull!"
# SPDX identifier
license            = "MIT"
#documentation      = "https://your.docs.url/here"
source             = "https://github.com/Luyten-Orion/FaePkg"
homepage           = "https://github.com/Luyten-Orion/FaePkg"
# When importing fae, `engine` would be moved under `fae`, so to require the
# `semver.nim` file, it'd be `import fae/semver`, if a project explicitly
# imports certain sourcesets, it'd be `import fae/engine/semver`.
default-sourcesets = ["engine"]

[package.ext]
tags = ["nimskull", "package-manager", "cli"]

[forges.gh]
origin = "git"
host   = "github.com"

[sourcesets.engine]
# TODO: Maybe this should be `src-dirs` and accept a list? Personally dislike
# idea though. Maybe `res-dir` should be a thing too? Though, not sure how we'd
# expose that to the sourceset code, maybe through a specific API? It'd probably
# be better if we just force the developer to figure it out tbh, especially
# since unlike Java, Skull doesn't have the concept of resources :p
src-dir = "engine"

[sourcesets.cli]
src-dir = "cli"
# Entries of `dependencies` in a sourceset definition must be a table.
# sourcesets inherit the `default-sourcesets` as dependencies by default.

# `fae` is a reserved scheme that refers to the current manifest.
dependencies = [{src = "fae:engine"}]

[sourcesets.test]
src-dir = "tests"

[[dependencies]]
src        = "gh:NimParsers/parsetoml"
# By default, it'll include all sourcesets besides `test`, but you can specify
# which ones the project requires, if you only require a few components rather
# than the entire package. Packages can also declare the sourcesets that can be
# included by default via `package.default-sourcesets`. Will move it to a
# different section for sure, just not sure where yet.
sourcesets = ["main"]
version    = "0.7.2"

[[dependencies]]
src     = "gh:disruptek/gittyup"
version = "3.2.2"

[[dependencies]]
src     = "gh:disruptek/gram"
version = "0.4.1"

# TODO: Features section