format = 0

[package]
# Must be the URI (without the scheme) of the package.
name = "github.com/luyten-orion/faepkg"

[dependencies.parsetoml]
src = "https://github.com/nimparsers/parsetoml.git"
# for subdirs: "https://github.com/nimparsers/parsetoml.git/subdir/if/applicable"
version    = "0.7.2"
foreign-pm = "nimble"

# Proposed syntax
#[features]
#defaults = ["foo", "bar"]
#groupa = ["foo", "alttoml"]
#groupb = ["bar", "richlog"]

#[features.foo.dependencies.alttoml]
#src        = "foo.bar/alttoml"
#origin     = "git"
#scheme     = "https"
#version    = "1.0.0"

#[features.bar.dependencies.richlog]
#src        = "foo.bar/richlog"
#origin     = "git"
#scheme     = "https"
#version    = "1.0.0"
